version: '3.8'

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_DB: ${DB_NAME:-feedback}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-feedback}
      - RUST_LOG=debug
    ports:
      - "5095:5095"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5090:5090"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: