version: '3.8'

services:
  db:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_DB: ${DB_NAME:-feedback}
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_NAME=${DB_NAME:-feedback}
    ports:
      - "5095:5095"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5090:5090"
    depends_on:
      - backend

volumes:
  postgres_data: